### ISSUE TITLE
debugging fails

### ISSUE THREAD

**Issue by exocode** [oneturkmen/nodejs-debugging#3]
First I check app with: `docker-compose -f docker-compose.yml up`-
`http://localhost:3000/greet` works. Then I stop it with `docker-compose down`.

Then I tried the debug with `docker-compose -f docker-compose.debug.yml up` which results in the expected:

```
api_1  |
api_1  | > app@1.0.0 debug /app
api_1  | > npm run build && node --inspect-brk=0.0.0.0:9229 ./dist/server.js
api_1  |
api_1  |
api_1  | > app@1.0.0 build /app
api_1  | > tsc
api_1  |
api_1  | Debugger listening on ws://0.0.0.0:9229/0f33e3bc-ea01-4929-b5fb-d6762774a12c
```

Now when I click the green triangle this is in my console the old debug process stops and I get

```
> Executing task: docker-compose -f docker-compose.debug.yml up <

Recreating nodejs-debugging_api_1 ... done
Attaching to nodejs-debugging_api_1
api_1  | 
api_1  | > app@1.0.0 debug /app
api_1  | > npm run build && node --inspect-brk=0.0.0.0:9229 ./dist/server.js
api_1  | 
api_1  | 
api_1  | > app@1.0.0 build /app
api_1  | > tsc
api_1  | 
api_1  | Debugger listening on ws://0.0.0.0:9229/7b956545-068c-479a-85a5-5fa0dae23d15
```

which looks legit, but after a few seconds I got this:

`The specified task cannot be tracked.`

<img width="892" alt="Bildschirmfoto 2019-03-29 um 01 46 31" src="https://user-images.githubusercontent.com/1597621/55201740-b5f9d600-51c4-11e9-99e1-416bf16e09d9.png">

Would you please so kind and help me to solve this "puzzle"? I am relatively new to VSCode and Node. 

Many thanks in advance

**Comment by oneturkmen** [comment]
Hey @exocode ,

Could you share your `tasks.json` as well as `launch.json` files?

**Comment by exocode** [comment]
of course, I didn't change anything (cloned repo only)

tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "launch-debug-container",
            "command": "docker-compose -f docker-compose.debug.yml up",
            "type": "shell",
            "group": "build",
            "isBackground": true
        },
        {
            "label": "end-debug-container",
            "command": "docker-compose -f docker-compose.debug.yml down",
            "type": "shell",
            "group": "build",
            "isBackground": true
        }
    ]
}

```

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Remote Debugging",
            "address": "0.0.0.0",
            "port":9229,
            "localRoot": "${workspaceFolder}/dist",
            "remoteRoot": "/app/dist",
            "protocol":"inspector",
            "timeout": 60000,
            "preLaunchTask": "launch-debug-container",
            "postDebugTask": "end-debug-container",
        }
    ]
}
```

**Comment by oneturkmen** [comment]
I suspect there may be a problem with VSCode's priviliges. Have you tried clicking *Debug Anyway* to see what it outputs?

**Comment by exocode** [comment]
Yes, that happened:

<img width="713" alt="Bildschirmfoto 2019-03-29 um 11 59 47" src="https://user-images.githubusercontent.com/1597621/55228353-2ed74d00-521a-11e9-8587-c08bc7a5edb4.png">

It seems, that I have an IP issue.

Seems

**Comment by exocode** [comment]
Jop, I changed my IP in launch.json and it worked!
Noob issue...
{
    "version": "0.2.0",
    "configurations": [{
        "type": "node",
        "request": "attach",
        "name": "Remote Debugging",
        **"address": "192.168.99.100",**
        "port": 9229,
        "localRoot": "${workspaceFolder}/dist",
        "remoteRoot": "/app/dist",
        "protocol": "inspector",
        "timeout": 60000,
        "preLaunchTask": "launch-debug-container",
        "postDebugTask": "end-debug-container",
    }]
}

Great, thank you for your time, sorry for making noise!

**Comment by oneturkmen** [comment]
@exocode No problem!
